HospitalJuancho/Models/Medicos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.IO;
using System.Data;
using System.ComponentModel.DataAnnotations;


namespace HospitalJuancho.Models
{
    public class Medicos
    {
        [Key]
        public int ID_Medico { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Exequatur { get; set; }
        [Required]
        public string Especialidad { get; set; }

        public Opcion opci { get; set; }


        public enum Opcion
        {
            Especialidad, Medico
        }
    }
}

HospitalJuancho/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalJuancho.Models;

namespace HospitalJuancho.Controllers
{
    public class MedicosController : Controller
    {
        private BDContext db = new BDContext();

        // GET: Medicos
        public ActionResult Index()
        {
            return View(db.Medicos.ToList());
        }
        [HttpPost]
        public ActionResult Index(string busqueda,string select)
        {

            if(select == "Nombre")
            {
                var abc = from a in db.Medicos
                          select a;
                abc = abc.Where(s => s.Nombre.Contains(busqueda));
                return View(abc);
            }
            if(select == "Especialidad")
            {
                var abc = from a in db.Medicos
                          where a.Especialidad == busqueda
                          select a;
                return View(abc);
              
            }
            return View(db.Medicos.ToList());
           
        }


        // GET: Medicos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // GET: Medicos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medicos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Medico,Nombre,Exequatur,Especialidad")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medicos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicos);
        }

        // GET: Medicos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: Medicos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Medico,Nombre,Exequatur,Especialidad")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicos);
        }

        // GET: Medicos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: Medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicos medicos = db.Medicos.Find(id);
            db.Medicos.Remove(medicos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
      
        }
    }

HospitalJuancho/Views/Medicos/Create.cshtml
@model HospitalJuancho.Models.Medicos

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exequatur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exequatur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exequatur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalJuancho/Views/Medicos/Delete.cshtml
@model HospitalJuancho.Models.Medicos

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>Estas seguro que desea Borrar?</h3>
<div>
    <h4>Medicos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exequatur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exequatur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Atras", "Index")
        </div>
    }
</div>

HospitalJuancho/Views/Medicos/Details.cshtml
@model HospitalJuancho.Models.Medicos

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Medicos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exequatur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exequatur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID_Medico }) |
    @Html.ActionLink("Atras", "Index")
</p>

HospitalJuancho/Views/Medicos/Edit.cshtml
@model HospitalJuancho.Models.Medicos

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Medico)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exequatur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exequatur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exequatur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atras", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalJuancho/Views/Medicos/Index.cshtml
@model IEnumerable<HospitalJuancho.Models.Medicos>



@{
    ViewBag.Title = "Index";
}

<h2>Medicos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>

    @using (Html.BeginForm("Index", "Medicos", FormMethod.Post))
    {
<div class="between">
    @Html.TextBox("busqueda", "", new { @class = "form-control mb-2", placeholder = "Buscar..." })
    <br />
    <select name="select" class="form-control col col-lg-2">
        <option value="">Elige una opcion</option>
        <option value="Nombre">Nombre</option>
        <option value="Especialidad">Especialidad</option>
    </select>

    <div class="col-2">
        <button type="submit" class="btn btn-success">Buscar</button>
    </div>
</div>
    }
<br />
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exequatur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Especialidad)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Exequatur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>

            <td class="btn btn-primary myBtn">
                @Html.ActionLink("Editar", "Edit", new { id = item.ID_Medico })
            </td>
            <td class="btn btn-danger myBtn">
                @Html.ActionLink("Eliminar", "Delete", new { id = item.ID_Medico })
            </td>
            <td class="btn btn-success myBtn">
                @Html.ActionLink("Detalles", "Details", new { id = item.ID_Medico })
            </td>
        </tr>
    }

</table>